spring:
  profiles: dev, default
  datasource:
    url: jdbc:mysql://localhost:3319/od?verifyServerCertificate\\=false&useSSL\\=true&characterEncoding\\=UTF-8
    password: d4t4b4s3
    username: root
  flyway:
    enabled: true

logging:
  level:
    root: INFO

server:
  port: 8081

---

spring:
  profiles: test
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver