spring:
  profiles: dev, default
  application:
      name: routes-service
  datasource:
#    url: jdbc:mysql://192.168.3.14:3319/od?verifyServerCertificate\\=false&useSSL\\=true&characterEncoding\\=UTF-8
#    password: d4t4b4s3
#    username: adidas_fan
    url: ${DB_URL:jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
  flyway:
    enabled: ${FLYWAY_ENABLE:true}

cors:
  url: ${CORS_URL:http://192.168.3.12:8082/}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

server:
  port: ${SERVER_PORT:8081}

auth:
  user: ${SEC_USER:admin}
  password: ${SEC_PW:adidas!}

eureka:
  client:
    service-url:
      defaultZone: ${URL_SPRING_CLOUD:http://localhost:8088/eureka}


---

spring:
  profiles: test
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver

auth:
  user: admin
  password: adidas!

cors:
  url: ${CORS_URL:http://localhost:8082/}